dist: trusty
sudo: required
language: python
python:
  - "3.6"

env:
  GOPATH: $HOME/go
  PATH: $GOPATH/bin:$PATH

install:
  - ./.bin/install_apt.sh
  - ./.bin/install_go.sh
  - ./.bin/install_npm.sh
  - pip install -r requirements.txt


script:
  - coala --ci
